<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <OutputType>Library</OutputType>
        <RootNamespace>TwitchTools.Client</RootNamespace>
        <AssemblyName>TwitchTools.Client</AssemblyName>
        <LangVersion>latest</LangVersion>
        <OutputPath>.bin\</OutputPath>
    </PropertyGroup>
    <ItemGroup>
        <Reference Include="UnityEngine">
            <HintPath>$(ManagedDir)UnityEngine.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.CoreModule">
            <HintPath>$(ManagedDir)UnityEngine.CoreModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityWebRequestModule">
            <HintPath>$(ManagedDir)UnityEngine.UnityWebRequestModule.dll</HintPath>
        </Reference>
        <Reference Include="Newtonsoft.Json">
            <HintPath>$(ManagedDir)Newtonsoft.Json.dll</HintPath>
        </Reference>
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="WebSocketSharp" Version="1.0.3-rc11" />
    </ItemGroup>
    <Target Name="CopyModDll" AfterTargets="Build">
        <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(BepInExPluginsDir)\TwitchTools\" />
    </Target>
</Project>